// <auto-generated />
// Manually written replacements for QCEDL.Analyzer source generator output
using System;

namespace Qualcomm.EmergencyDownload.ChipInfo
{
    internal static class QualcommPartNumbersExtensions
    {
        internal static string ToStringSnakeCaseUpper(this QualcommPartNumbers value)
        {
            return value switch
            {
                QualcommPartNumbers.Mdm9250 => "MDM_9250",
                QualcommPartNumbers.Mdm9255 => "MDM_9255",
                QualcommPartNumbers.Mdm9350 => "MDM_9350",
                QualcommPartNumbers.Mdm9650 => "MDM_9650",
                QualcommPartNumbers.Mdm9655 => "MDM_9655",
                QualcommPartNumbers.Apq8096 => "APQ_8096",
                QualcommPartNumbers.Msm8998 => "MSM_8998",
                QualcommPartNumbers.Msm8996Sg => "MSM_8996_SG",
                QualcommPartNumbers.Apq8098 => "APQ_8098",
                QualcommPartNumbers.Apq8096Sg => "APQ_8096_SG",
                QualcommPartNumbers.Msm8997 => "MSM_8997",
                QualcommPartNumbers.Msm8996Sgau => "MSM_8996_SGAU",
                QualcommPartNumbers.Apq8096Sgau => "APQ_8096_SGAU",
                QualcommPartNumbers.Mdm9660OrSdm660 => "MDM_9660_OR_SDM_660",
                QualcommPartNumbers.Sdm630 => "SDM_630",
                QualcommPartNumbers.Mdm9665 => "MDM_9665",
                QualcommPartNumbers.Sdm845 => "SDM_845",
                QualcommPartNumbers.Sdc845 => "SDC_845",
                QualcommPartNumbers.Sdm830 => "SDM_830",
                QualcommPartNumbers.Sdm670 => "SDM_670",
                QualcommPartNumbers.Sdc830 => "SDC_830",
                QualcommPartNumbers.Sda670 => "SDA_670",
                QualcommPartNumbers.Sdm640 => "SDM_640",
                QualcommPartNumbers.Sdx24 => "SDX_24",
                QualcommPartNumbers.Sdx24M => "SDX_24M",
                QualcommPartNumbers.Sdm450 => "SDM_450",
                QualcommPartNumbers.Sdm855 => "SDM_855",
                QualcommPartNumbers.Sda855 => "SDA_855",
                QualcommPartNumbers.Qcs605 => "QCS_605",
                QualcommPartNumbers.Sdm1000 => "SDM_1000",
                QualcommPartNumbers.Sda865 => "SDA_865",
                QualcommPartNumbers.Sdm855A => "SDM_855A",
                QualcommPartNumbers.Sdx55 => "SDX_55",
                QualcommPartNumbers.Qca6390 => "QCA_6390",
                QualcommPartNumbers.Sm7150 => "SM_7150",
                QualcommPartNumbers.Sm7150P => "SM_7150P",
                QualcommPartNumbers.Sa8150 => "SA_8150",
                QualcommPartNumbers.Sa8150P => "SA_8150P",
                QualcommPartNumbers.Sm6150P => "SM_6150P",
                QualcommPartNumbers.Sa6155P => "SA_6155P",
                QualcommPartNumbers.Sa6150P => "SA_6150P",
                QualcommPartNumbers.Sa6145P => "SA_6145P",
                QualcommPartNumbers.Sa4155P => "SA_4155P",
                QualcommPartNumbers.SmLahaina => "SM_LAHAINA",
                QualcommPartNumbers.SmpLahaina => "SMP_LAHAINA",
                QualcommPartNumbers.ScMakena => "SC_MAKENA",
                QualcommPartNumbers.SaMakenaIvi => "SA_MAKENA_IVI",
                QualcommPartNumbers.SaMakenaAdas => "SA_MAKENA_ADAS",
                QualcommPartNumbers.SmLahainaModule => "SM_LAHAINA_MODULE",
                QualcommPartNumbers.SmCedros => "SM_CEDROS",
                QualcommPartNumbers.SmKodiak => "SM_KODIAK",
                QualcommPartNumbers.ScKodiakChrome => "SC_KODIAK_CHROME",
                QualcommPartNumbers.ScKodiakWindows => "SC_KODIAK_WINDOWS",
                QualcommPartNumbers.QcmKodiak => "QCM_KODIAK",
                QualcommPartNumbers.QcsKodiak => "QCS_KODIAK",
                QualcommPartNumbers.SmLahainaLteOnly => "SM_LAHAINA_LTE_ONLY",
                QualcommPartNumbers.SmpKodiak => "SMP_KODIAK",
                QualcommPartNumbers.SmpLahainaOemSpecific => "SMP_LAHAINA_OEM_SPECIFIC",
                QualcommPartNumbers.SmKodiakLteOnly => "SM_KODIAK_LTE_ONLY",
                QualcommPartNumbers.ScpKodiak => "SCP_KODIAK",
                QualcommPartNumbers.Msm8916 => "MSM_8916",
                QualcommPartNumbers.Msm8974 => "MSM_8974",
                QualcommPartNumbers.Msm8674 => "MSM_8674",
                QualcommPartNumbers.Msm8274 => "MSM_8274",
                QualcommPartNumbers.Apq8074 => "APQ_8074",
                QualcommPartNumbers.Msm8974Pro => "MSM_8974_PRO",
                QualcommPartNumbers.Msm8674Pro => "MSM_8674_PRO",
                QualcommPartNumbers.Msm8274Pro => "MSM_8274_PRO",
                QualcommPartNumbers.Apq8074Pro => "APQ_8074_PRO",
                QualcommPartNumbers.Msm8974Ab => "MSM_8974_AB",
                QualcommPartNumbers.Msm8674Ab => "MSM_8674_AB",
                QualcommPartNumbers.Msm8274Ab => "MSM_8274_AB",
                QualcommPartNumbers.Apq8074Ab => "APQ_8074_AB",
                QualcommPartNumbers.Msm8974Aa => "MSM_8974_AA",
                QualcommPartNumbers.Msm8674Aa => "MSM_8674_AA",
                QualcommPartNumbers.Msm8274Aa => "MSM_8274_AA",
                QualcommPartNumbers.Apq8074Aa => "APQ_8074_AA",
                QualcommPartNumbers.Mdm8225 => "MDM_8225",
                QualcommPartNumbers.Mdm9225OrMdm92251 => "MDM_9225_OR_MDM_92251",
                QualcommPartNumbers.Mdm9225MorMdm9225M1 => "MDM_9225M_OR_MDM_9225M1",
                QualcommPartNumbers.Mdm8225M => "MDM_8225M",
                QualcommPartNumbers.Mdm9625 => "MDM_9625",
                QualcommPartNumbers.Mdm9625M => "MDM_9625M",
                QualcommPartNumbers.Mdm9320 => "MDM_9320",
                QualcommPartNumbers.Msm8226 => "MSM_8226",
                QualcommPartNumbers.Msm8626 => "MSM_8626",
                QualcommPartNumbers.Msm8526 => "MSM_8526",
                QualcommPartNumbers.Msm8126 => "MSM_8126",
                QualcommPartNumbers.Apq8026 => "APQ_8026",
                QualcommPartNumbers.Msm8926 => "MSM_8926",
                QualcommPartNumbers.Msm8326 => "MSM_8326",
                QualcommPartNumbers.Fsm9965 => "FSM_9965",
                QualcommPartNumbers.Fsm9955 => "FSM_9955",
                QualcommPartNumbers.Fsm9950 => "FSM_9950",
                QualcommPartNumbers.Fsm9915 => "FSM_9915",
                QualcommPartNumbers.Fsm9910 => "FSM_9910",
                QualcommPartNumbers.Fsm9900 => "FSM_9900",
                QualcommPartNumbers.Msm8110 => "MSM_8110",
                QualcommPartNumbers.Msm8210 => "MSM_8210",
                QualcommPartNumbers.Msm8610 => "MSM_8610",
                QualcommPartNumbers.Msm8810 => "MSM_8810",
                QualcommPartNumbers.Msm8212 => "MSM_8212",
                QualcommPartNumbers.Msm8612 => "MSM_8612",
                QualcommPartNumbers.Msm8112 => "MSM_8112",
                QualcommPartNumbers.Msm8510 => "MSM_8510",
                QualcommPartNumbers.Msm8512 => "MSM_8512",
                QualcommPartNumbers.Apq80840 => "APQ_80840",
                QualcommPartNumbers.Apq80841 => "APQ_80841",
                QualcommPartNumbers.Msm8962 => "MSM_8962",
                QualcommPartNumbers.Msm8262 => "MSM_8262",
                QualcommPartNumbers.Apq8062 => "APQ_8062",
                QualcommPartNumbers.Apq8028 => "APQ_8028",
                QualcommPartNumbers.Msm8128 => "MSM_8128",
                QualcommPartNumbers.Msm8228 => "MSM_8228",
                QualcommPartNumbers.Msm8528 => "MSM_8528",
                QualcommPartNumbers.Msm8628 => "MSM_8628",
                QualcommPartNumbers.Msm8928 => "MSM_8928",
                QualcommPartNumbers.Mdm9630 => "MDM_9630",
                QualcommPartNumbers.Mdm9635M => "MDM_9635M",
                QualcommPartNumbers.Mdm9230 => "MDM_9230",
                QualcommPartNumbers.Mdm9235M => "MDM_9235M",
                QualcommPartNumbers.Mdm8630 => "MDM_8630",
                QualcommPartNumbers.Mdm9330 => "MDM_9330",
                QualcommPartNumbers.Mpq8092 => "MPQ_8092",
                QualcommPartNumbers.Msm8994 => "MSM_8994",
                QualcommPartNumbers.Qdf2432 => "QDF_2432",
                QualcommPartNumbers.Msm8996 => "MSM_8996",
                QualcommPartNumbers.Mdm9640 => "MDM_9640",
                QualcommPartNumbers.Mdm9240 => "MDM_9240",
                QualcommPartNumbers.Mdm9340 => "MDM_9340",
                QualcommPartNumbers.Mdm9645 => "MDM_9645",
                QualcommPartNumbers.Mdm9245 => "MDM_9245",
                _ => value.ToString(),
            };
        }
    }
}

namespace Qualcomm.EmergencyDownload.Layers.APSS.Firehose.Xml.Elements
{
    internal static class StorageTypeExtensions
    {
        internal static string ToStringFast(this StorageType value)
        {
            return value switch
            {
                StorageType.Sdcc => "eMMC",
                StorageType.Spinor => "spinor",
                StorageType.Ufs => "UFS",
                StorageType.Nand => "nand",
                StorageType.Nvme => "NVMe",
                _ => value.ToString(),
            };
        }
    }

    internal static class PowerValueExtensions
    {
        internal static string ToStringFast(this PowerValue value)
        {
            return value switch
            {
                PowerValue.Reset => "reset",
                PowerValue.Off => "off",
                PowerValue.Edl => "reset_to_edl",
                _ => value.ToString(),
            };
        }
    }
}
